import numpy as np 
array1=np.array([[1,2,3],[4,5,6]]) 
array2=np.array([[7,8,9],[10,11,12]])
sum_arrays=array1+array2
print("sum of two arrays:") 
print(sum_arrays) 
total_sum=np.sum(sum_arrays) 
print("\n Sum of all array elements:",total_sum)
sqrt_array1=np.sqrt(array1)
sqrt_array2=np.sqrt(array2)
print("Square root of array1:",sqrt_array1)
column_sum_array1=np.sum(array1,axis=0)
print("\n Sum of each column of array1:",column_sum_array1)
row_sum_array1=np.sum(array1,axis=1)
print("\n Sum of each row of array1:",row_sum_array1)
transpose_array1=np.transpose(array1)
print("\n Transpose of array1:",transpose_array1)